spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB


zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    user:
      path: /user/**
      service-id: user
    question:
      path: /question/**
      service-id: question
    story:
      path: /story/**
      service-id: story
    city:
      path: /city/**
      service-id: city
    im:
      path: /im/**
      service-id: im
    system:
      path: /system/**
      service-id: system
    search:
      path: /search/**
      service-id: search
    pay:
      path: /pay/**
      service-id: pay
    share:
      path: /share/**
      service-id: share
    jms:
      path: /jms/**
      service-id: jms
    job:
      path: /job/**
      service-id: job
    manage:
      path: /manage/**
      service-id: manage
  add-proxy-headers: true
  add-host-header: true
